# Generated by Django 5.2.1 on 2026-05-16 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ceo", "Chief Executive Officer (CEO)"),
                            ("cto", "Chief Technology Officer (CTO)"),
                            ("coo", "Chief Operating Officer (COO)"),
                            ("cfo", "Chief Financial Officer (CFO)"),
                            ("engineering_manager", "Engineering Manager"),
                            ("project_manager", "Project Manager"),
                            ("product_manager", "Product Manager"),
                            ("delivery_manager", "Delivery Manager"),
                            ("operations_manager", "Operations Manager"),
                            ("hr_manager", "HR Manager"),
                            ("sales_manager", "Sales Manager"),
                            ("fullstack_developer", "Full Stack Developer"),
                            ("frontend_developer", "Frontend Developer"),
                            ("backend_developer", "Backend Developer"),
                            ("mobile_developer", "Mobile Developer"),
                            ("software_engineer", "Software Engineer"),
                            ("db_handler", "Database Handler / DBA"),
                            ("db_architect", "Database Architect"),
                            ("devops_engineer", "DevOps Engineer"),
                            ("cloud_engineer", "Cloud Engineer"),
                            ("network_engineer", "Network Engineer"),
                            ("security_engineer", "Security Engineer"),
                            ("quality_lead", "Quality Lead"),
                            ("qa_engineer", "QA Engineer / Tester"),
                            ("automation_tester", "Automation Tester"),
                            ("manual_tester", "Manual Tester"),
                            ("performance_tester", "Performance Tester"),
                            ("ui_ux_designer", "UI/UX Designer"),
                            ("product_designer", "Product Designer"),
                            ("graphic_designer", "Graphic Designer"),
                            ("data_scientist", "Data Scientist"),
                            ("data_analyst", "Data Analyst"),
                            ("data_engineer", "Data Engineer"),
                            ("ml_engineer", "ML / AI Engineer"),
                            ("business_analyst", "Business Analyst"),
                            ("scrum_master", "Scrum Master"),
                            ("technical_lead", "Technical Lead"),
                            ("consultant", "Consultant"),
                            ("support_engineer", "Support Engineer"),
                            ("intern", "Intern"),
                            ("student", "Student"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=300)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("avatar_color", models.CharField(default="#7c3aed", max_length=7)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
